### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by zwyzzz888** [emkutuk/wow-fishing-bot#1]
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
========== RESTART: C:\Users\a\Downloads\wow-fishing-bot-main\main.py ==========
Bot is starting in 3
Bot is starting in 2
Bot is starting in 1
Bot has started...
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Caught the fish!
Throwing the pole...
Catching some fish...
Traceback (most recent call last):
  File "C:\Users\a\Downloads\wow-fishing-bot-main\main.py", line 78, in <module>
    WoWBot()
  File "C:\Users\a\Downloads\wow-fishing-bot-main\main.py", line 21, in __init__
    self.catch_fish()
  File "C:\Users\a\Downloads\wow-fishing-bot-main\main.py", line 34, in catch_fish
    self.take_screenshot()
  File "C:\Users\a\Downloads\wow-fishing-bot-main\main.py", line 61, in take_screenshot
    pyautogui.screenshot("media/myscreenshot.jpg")
  File "D:\Program Files\python\lib\site-packages\pyscreeze\__init__.py", line 135, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\pyscreeze\__init__.py", line 433, in _screenshot_win32
    im.save(imageFilename)
  File "D:\Program Files\python\lib\site-packages\PIL\Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'media/myscreenshot.jpg'

**Comment by emkutuk** [comment]
its strange that it did this, Errno22 is normally caused by invalid characters in the file name like ":" or "\". Regardless tho, im pushing a small fix :)
